### ISSUE TITLE
GFX gui segfaults on ubuntu 14.04, nvidia-346

### ISSUE THREAD

**Issue by tingelst** [wolftype/gfx#1]
The examples with a call to `gui()` in `setup()` segfaults on ubuntu 14.04 with nvidia-346 driver. I have debugged it down to the 3rd call to `OnDraw()` in `gfx_control.h`. 

Seems like a problem with `mWindowEventHandlers`

The examples compile and run when the call to `gui` is commented out.

**Comment by wolftype** [comment]
do you know if the glv library examples in vsr/ext/glv compile on that machine?

for instance:

cd ext/glv
make example/dataPlot.cpp

thanks!
pablo

**Comment by tingelst** [comment]
Yep, they all compile and run.

**Comment by tingelst** [comment]
This issue should be in https://github.com/wolftype/versor. I'll close this and reopen there.
